// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parko.Data;

#nullable disable

namespace Parko.Migrations
{
    [DbContext(typeof(ParkoDbContext))]
    partial class ParkoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parko.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVip")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParkingSpaceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("ReleaseTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UsedPoint")
                        .HasColumnType("bit");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpaceId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Parko.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Parko.Models.ParkingSpace", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpaces");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        },
                        new
                        {
                            Id = 9
                        },
                        new
                        {
                            Id = 10
                        },
                        new
                        {
                            Id = 11
                        },
                        new
                        {
                            Id = 12
                        },
                        new
                        {
                            Id = 13
                        },
                        new
                        {
                            Id = 14
                        },
                        new
                        {
                            Id = 15
                        },
                        new
                        {
                            Id = 16
                        },
                        new
                        {
                            Id = 17
                        },
                        new
                        {
                            Id = 18
                        },
                        new
                        {
                            Id = 19
                        },
                        new
                        {
                            Id = 20
                        },
                        new
                        {
                            Id = 21
                        },
                        new
                        {
                            Id = 22
                        },
                        new
                        {
                            Id = 23
                        },
                        new
                        {
                            Id = 24
                        },
                        new
                        {
                            Id = 25
                        },
                        new
                        {
                            Id = 26
                        },
                        new
                        {
                            Id = 27
                        },
                        new
                        {
                            Id = 28
                        },
                        new
                        {
                            Id = 29
                        },
                        new
                        {
                            Id = 30
                        },
                        new
                        {
                            Id = 31
                        },
                        new
                        {
                            Id = 32
                        },
                        new
                        {
                            Id = 33
                        },
                        new
                        {
                            Id = 34
                        },
                        new
                        {
                            Id = 35
                        },
                        new
                        {
                            Id = 36
                        },
                        new
                        {
                            Id = 37
                        },
                        new
                        {
                            Id = 38
                        },
                        new
                        {
                            Id = 39
                        },
                        new
                        {
                            Id = 40
                        },
                        new
                        {
                            Id = 41
                        },
                        new
                        {
                            Id = 42
                        },
                        new
                        {
                            Id = 43
                        },
                        new
                        {
                            Id = 44
                        },
                        new
                        {
                            Id = 45
                        },
                        new
                        {
                            Id = 46
                        },
                        new
                        {
                            Id = 47
                        },
                        new
                        {
                            Id = 48
                        },
                        new
                        {
                            Id = 49
                        },
                        new
                        {
                            Id = 50
                        },
                        new
                        {
                            Id = 51
                        },
                        new
                        {
                            Id = 52
                        },
                        new
                        {
                            Id = 53
                        },
                        new
                        {
                            Id = 54
                        },
                        new
                        {
                            Id = 55
                        },
                        new
                        {
                            Id = 56
                        },
                        new
                        {
                            Id = 57
                        },
                        new
                        {
                            Id = 58
                        },
                        new
                        {
                            Id = 59
                        },
                        new
                        {
                            Id = 60
                        },
                        new
                        {
                            Id = 61
                        },
                        new
                        {
                            Id = 62
                        },
                        new
                        {
                            Id = 63
                        },
                        new
                        {
                            Id = 64
                        },
                        new
                        {
                            Id = 65
                        },
                        new
                        {
                            Id = 66
                        },
                        new
                        {
                            Id = 67
                        },
                        new
                        {
                            Id = 68
                        },
                        new
                        {
                            Id = 69
                        },
                        new
                        {
                            Id = 70
                        },
                        new
                        {
                            Id = 71
                        },
                        new
                        {
                            Id = 72
                        },
                        new
                        {
                            Id = 73
                        },
                        new
                        {
                            Id = 74
                        },
                        new
                        {
                            Id = 75
                        },
                        new
                        {
                            Id = 76
                        },
                        new
                        {
                            Id = 77
                        },
                        new
                        {
                            Id = 78
                        },
                        new
                        {
                            Id = 79
                        },
                        new
                        {
                            Id = 80
                        },
                        new
                        {
                            Id = 81
                        },
                        new
                        {
                            Id = 82
                        },
                        new
                        {
                            Id = 83
                        },
                        new
                        {
                            Id = 84
                        },
                        new
                        {
                            Id = 85
                        },
                        new
                        {
                            Id = 86
                        },
                        new
                        {
                            Id = 87
                        },
                        new
                        {
                            Id = 88
                        },
                        new
                        {
                            Id = 89
                        },
                        new
                        {
                            Id = 90
                        },
                        new
                        {
                            Id = 91
                        },
                        new
                        {
                            Id = 92
                        },
                        new
                        {
                            Id = 93
                        },
                        new
                        {
                            Id = 94
                        },
                        new
                        {
                            Id = 95
                        },
                        new
                        {
                            Id = 96
                        },
                        new
                        {
                            Id = 97
                        },
                        new
                        {
                            Id = 98
                        },
                        new
                        {
                            Id = 99
                        },
                        new
                        {
                            Id = 100
                        });
                });

            modelBuilder.Entity("Parko.Models.VipCarRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Vehicle")
                        .IsUnique();

                    b.ToTable("VipCarRecords");
                });

            modelBuilder.Entity("Parko.Models.VipPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastReset")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("VipPoints");
                });

            modelBuilder.Entity("Parko.Models.Car", b =>
                {
                    b.HasOne("Parko.Models.ParkingSpace", "ParkingSpace")
                        .WithMany("Cars")
                        .HasForeignKey("ParkingSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingSpace");
                });

            modelBuilder.Entity("Parko.Models.VipCarRecord", b =>
                {
                    b.HasOne("Parko.Models.Client", "Client")
                        .WithMany("VipCarRecords")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Parko.Models.VipPoint", b =>
                {
                    b.HasOne("Parko.Models.Client", null)
                        .WithOne("VipPoint")
                        .HasForeignKey("Parko.Models.VipPoint", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parko.Models.Client", b =>
                {
                    b.Navigation("VipCarRecords");

                    b.Navigation("VipPoint");
                });

            modelBuilder.Entity("Parko.Models.ParkingSpace", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
